export const sociosInitialForm = () => ({
    nombre: '',
    apellido: '',
    cedula: '',
    estadoCivilId: null,
    fechaNacimiento: new Date().toISOString(),
    lugar: '',
    genero: 'M',
    nacionalidadId: null,
    gradoAcademico: '',
    motivo: '',
    correspondencia: 'particular',
    direccionParticular: {
        calleYNumero: '',
        ciudadId: '',
        barrioId: '',
        telefono: '',
        celular: '',
        correo: '',
    },
    conyugue: {
        nombre: '',
        apellido: '',
        cedula: '',
        fechaNacimiento: '',
        lugar: '',
    },
    hijos: [{
        nombre: '',
        apellido: '',
        cedula: '',
        fechaNacimiento: '',        
    }],
    domicilioLaboral: {
        calleYNumero: '',
        ciudadId: '',
        barrioId: '',
        telefono: '',
        celular: '',
        correo: '',
    },
    antiguedad: '',
    nombreEmpresa: '',
    esEmpleado: "false",
    profesionId: null,
    puestoLaboralId: null,
    actividadEmpresa: null,
    ingresoMensual: null,
    otroIngreso: "false",
    otroMonto: '',
    otroConcepto: '',
    latitud: '',
    longitud: '',
});