export const sociosInitialForm = () => ({
    nombre: '',
    apellido: '',
    cedula: '',
    estadoCivilId: null,
    fechaNacimiento: new Date().toISOString(),
    lugar: '',
    genero: 'M',
    nacionalidadId: null,
    gradoAcademico: '',
    motivo: '',
    correspondencia: 'particular',
    // direccionParticular: {
    //     calleYNumero: '',
    //     ciudadId: '',
    //     barrioId: '',
    //     telefono: '',
    //     celular: '',
    //     correo: '',
    // },
    // direccionParticular: null,
    // conyugue: null,   
    hijos: [],
    // domicilioLaboral: {
    //     calleYNumero: '',
    //     ciudadId: '',
    //     barrioId: '',
    //     telefono: '',
    //     celular: '',
    //     correo: '',
    // },
    // domicilioLaboral: null,
    antiguedad: 0,
    nombreEmpresa: '',
    esEmpleado: "false",
    profesionId: null,
    puestoLaboralId: null,
    actividadEmpresa: '',
    ingresoMensual: '0',
    otroIngreso: "false",
    otroMonto: '0',
    otroConcepto: '',
    latitud: '',
    longitud: '',
});